### DB ###
;
DROP DATABASE IF EXISTS DB_HOSPEDAGEM
;
CREATE DATABASE DB_HOSPEDAGEM
;
USE DB_HOSPEDAGEM

;
CREATE TABLE `TB_USERS` (
  `PK_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_LOGIN` VARCHAR(60) DEFAULT NULL,
  `DS_PASSWORD` VARCHAR(256) NOT NULL,
  `DS_EMAIL` VARCHAR(128) NOT NULL,
  `TG_ADMIN` INT,
  `TG_INATIVO` INT,
  `DH_INCLUSAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PK_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=LATIN1
;
INSERT INTO TB_USERS (DS_LOGIN, DS_PASSWORD, DS_EMAIL, TG_ADMIN) VALUES ('admin', '$2y$12$0tpKS5a.GAhYhTA4y2evze/TvlEIJHBZqcQxzeou8DvSbVuersOTi', 'alefspam007@gmail.com', 1)
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_USERS_SAVE`(
PDS_LOGIN VARCHAR(60),
PDS_PASSWORD VARCHAR(256),
PDS_EMAIL VARCHAR(128),
PTG_ADMIN INT(11)
)
BEGIN
    INSERT INTO TB_USERS (DS_LOGIN, DS_PASSWORD, DS_EMAIL, TG_ADMIN)
    VALUES(PDS_LOGIN, PDS_PASSWORD, PDS_EMAIL, PTG_ADMIN);

    SELECT * FROM TB_USERS A WHERE A.PK_ID= LAST_INSERT_ID();
END $$
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_USERSUPDATE_SAVE`(
PPK_ID INT,
PDS_LOGIN VARCHAR(60),
PDS_EMAIL VARCHAR(128),
PTG_ADMIN INT(11)
)
BEGIN
    UPDATE TB_USERS SET DS_LOGIN = PDS_LOGIN, DS_EMAIL = PDS_EMAIL, TG_ADMIN = PTG_ADMIN WHERE PK_ID = PPK_ID;

    SELECT * FROM TB_USERS A WHERE A.PK_ID = PPK_ID;
END$$

;
CREATE TABLE `TB_USERSPASSRECOVER` (
  `PK_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_USUARIO` INT(11) NOT NULL,
  `DS_IP` VARCHAR(45) NOT NULL,
  `DT_RECUPERACAO` DATETIME DEFAULT NULL,
  `TG_INATIVO` INT,
  `DT_INCLUSAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PK_ID`),
  CONSTRAINT FOREIGN KEY FK_USUARIO(FK_USUARIO) REFERENCES TB_USERS(PK_ID)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=LATIN1
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_USERSPASSRECOVER_CREATE`(
PFK_USUARIO INT,
PDS_IP VARCHAR(45)
)
BEGIN

	INSERT INTO TB_USERSPASSRECOVER (FK_USUARIO, DS_IP)
    VALUES(PFK_USUARIO, PDS_IP);

    SELECT * FROM TB_USERSPASSRECOVER
    WHERE PK_ID = LAST_INSERT_ID();

END$$

;
CREATE TABLE `TB_ITENS` (
  `PK_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_NOME` VARCHAR(60) DEFAULT NULL,
  `DS_DESCRICAO` VARCHAR(256) NOT NULL,
  `TG_INATIVO` INT,
  `DH_INCLUSAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PK_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=LATIN1
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ITENS_SAVE`(
PDS_NOME VARCHAR(60),
PDS_DESCRICAO VARCHAR(256)
)
BEGIN
    INSERT INTO TB_ITENS (DS_NOME, DS_DESCRICAO)
    VALUES(PDS_NOME, PDS_DESCRICAO);

    SELECT * FROM TB_ITENS A WHERE A.PK_ID= LAST_INSERT_ID();
END$$

;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ITENSUPDATE_SAVE`(
PPK_ID INT,
PDS_NOME VARCHAR(60),
PDS_DESCRICAO VARCHAR(128)
)
BEGIN
    UPDATE TB_ITENS SET DS_NOME = PDS_NOME, DS_DESCRICAO = PDS_DESCRICAO WHERE PK_ID = PPK_ID;

    SELECT * FROM TB_ITENS A WHERE A.PK_ID = PPK_ID;
END$$
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ITENS_DELETE`(
PPK_ID INT
)
BEGIN
	DELETE FROM TB_ITENS WHERE PK_ID = PPK_ID;
END$$

;
CREATE TABLE `TB_QUARTOS` (
  `PK_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DS_NOME` VARCHAR(60) DEFAULT NULL,
  `DS_DESCRICAO` VARCHAR(256) NOT NULL,
  `TG_INATIVO` INT,
  `DH_INCLUSAO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PK_ID`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=LATIN1
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_QUARTOS_SALVAR`(
PDS_NOME VARCHAR(60),
PDS_DESCRICAO VARCHAR(256)
)
BEGIN
    INSERT INTO TB_QUARTOS (DS_NOME, DS_DESCRICAO)
    VALUES(PDS_NOME, PDS_DESCRICAO);

    SELECT * FROM TB_QUARTOS A WHERE A.PK_ID = LAST_INSERT_ID();
END$$

;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_QUARTOS_ATUALIZAR`(
PPK_ID INT,
PDS_NOME VARCHAR(60),
PDS_DESCRICAO VARCHAR(128)
)
BEGIN
    UPDATE TB_QUARTOS SET DS_NOME = PDS_NOME, DS_DESCRICAO = PDS_DESCRICAO WHERE PK_ID = PPK_ID;

    SELECT * FROM TB_QUARTOS A WHERE A.PK_ID = PPK_ID;
END$$
;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_QUARTOS_DELETAR`(
PPK_ID INT
)
BEGIN
	DELETE FROM TB_QUARTOS WHERE PK_ID = PPK_ID;
END$$
